apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-oxpf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0046-tenant/tkrw-pr712-0075-0046-app/devfile-sample-oxpf@sha256:17e466b74a2ee7fb3d50427b233f09ebac53d22080fea4bf901bb6733aa0ddc1
        name: my-nodejs
        resources: {}
status: {}
